#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/sbin:${PATH}
set -e
if [ -f /usr/share/emscripten/.emscripten ]
then
	cp /usr/share/emscripten/.emscripten emscripten_config;
	sed -Ei '/^FROZEN_CACHE/d' emscripten_config;
	echo -e generate done!;
fi
